"""
Django settings for chemicaldatasheets project.

Generated by 'django-admin startproject' using Django 1.11.7.

For more information on this file, see
https://docs.djangoproject.com/en/1.11/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.11/ref/settings/
"""

DEFAULT_AUTO_FIELD='django.db.models.AutoField' 


import os
from platform import node as platform_hostname

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.11/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '<{42.hA5@_Pg\Q,Bw[*9e<)sfw+bmMVtA3HFV,8?a8?y6urXB_'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = [
                    'localhost', '127.0.0.1', '0.0.0.0',
                    'www.geller.co.nz', 'geller.co.nz', '157.245.125.77', '104.236.249.246',
                    'geller.work.gd', 'www.geller.work.gd',
                    'geller2.work.gd', 'www.geller2.work.gd',
                    '67d6-121-98-82-132.ngrok-free.app',
                    'geller2025-production-4bef.up.railway.app'
                ]

DEBUG_HOSTS = ('josh-ubuntu', 'Chriss-MacBook-Pro.local', 'Chriss-MBP', 'Chriss-Mac-mini.local',)
if platform_hostname() in DEBUG_HOSTS:
    DEBUG = True

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework.authtoken',
    'chemsapp',
    'corsheaders',
    'import_export',
    'ckeditor',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

CORS_ORIGIN_ALLOW_ALL = True
CORS_ALLOW_HEADERS = '*'
CORS_ALLOW_METHODS = '*'
ROOT_URLCONF = 'chemicaldatasheets.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': ['.//templates',],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.media',
            ],
        },
    },
]

LOGIN_REDIRECT_URL = '/'

WSGI_APPLICATION = 'chemicaldatasheets.wsgi.application'
APPEND_SLASH=True

# Database
# https://docs.djangoproject.com/en/1.11/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
#     }
# }
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.getenv('PGDATABASE', 'railway'),
        'USER': os.getenv('PGUSER', 'postgres'),
        'PASSWORD': os.getenv('PGPASSWORD', 'PWYTQNKQXOJoTsQmVljvcyJFtEICRyeS'),
        'HOST': os.getenv('PGHOST', 'switchyard.proxy.rlwy.net'),  # Use Railway internal host
        'PORT': os.getenv('PGPORT', '41935'),
    }
}

# import os
# from urllib.parse import urlparse

# # Fetch the DATABASE_URL from environment variables (for private Railway connection)
# DATABASE_URL = os.getenv('DATABASE_URL')

# # If DATABASE_URL is not set, fallback to using individual variables
# if DATABASE_URL:
#     # Parse the DATABASE_URL using urllib's urlparse to extract the components
#     url = urlparse(DATABASE_URL)
#     DATABASES = {
#         'default': {
#             'ENGINE': 'django.db.backends.postgresql',
#             'NAME': url.path[1:],  # Remove leading '/' from the path
#             'USER': url.username,
#             'PASSWORD': url.password,
#             'HOST': url.hostname,
#             'PORT': url.port,
#         }
#     }
# else:
#     # Fallback to individual environment variables if DATABASE_URL is not provided
# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.postgresql',
#         'NAME': os.getenv('PGDATABASE', 'railway'),
#         'USER': os.getenv('PGUSER', 'postgres'),
#         'PASSWORD': os.getenv('PGPASSWORD', 'PWYTQNKQXOJoTsQmVljvcyJFtEICRyeS'),
#         'HOST': os.getenv('PGHOST', 'switchyard.proxy.rlwy.net'),  # Use Railway internal host
#         'PORT': os.getenv('PGPORT', '41935'),
#     }
# }


REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework.authentication.TokenAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    )
}

# Password validation
# https://docs.djangoproject.com/en/1.11/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/1.11/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.11/howto/static-files/

STATIC_URL = '/static/'
MEDIA_URL = '/media/'
MEDIA_ROOT = '/data'
#MEDIA_ROOT = os.path.join(CHEMS_APP_DIR, 'media')

CHEMS_APP_DIR = os.path.join(BASE_DIR, 'chemsapp')
MAIN_DIR = os.path.join(BASE_DIR, 'chemicaldatasheets')

STATICFILES_DIRS = [
    os.path.join(CHEMS_APP_DIR, 'static', 'chemsapp'),
]
PROJECT_DIR = os.path.dirname(os.path.abspath(__file__))
STATIC_ROOT = os.path.join(BASE_DIR, 'dist_static')
#media files where uploaded files go to


CKEDITOR_CONFIGS = {
    'default': {
        'toolbar': 'Custom',
        'toolbar_Custom': [
            ['Bold', 'Italic', 'Underline'],
            ['NumberedList', 'BulletedList', '-', 'Outdent', 'Indent', '-', 'JustifyLeft', 'JustifyCenter', 'JustifyRight', 'JustifyBlock'],
            ['Link', 'Unlink'],
            ['RemoveFormat', 'Source']
        ]
    }
}






#email settings
EMAIL_HOST = 'mail.smtp2go.com'
EMAIL_HOST_USER = 'integra-505853'
EMAIL_HOST_PASSWORD = 'lGypy7pWbMVntlVE'
EMAIL_PORT = 2525
EMAIL_USE_TLS = True

EMAIL_FROM = 'Geller <info@geller.brush.co.nz>'
EMAIL_ADMIN = 'sales.support@integraindustries.co.nz'

RECAPTCHA_SITE_KEY = "6LcimBYiAAAAAGfPVreKgk5Ieg71YhFbvkJAt1MZ"
RECAPTCHA_PRIVATE_KEY = "6LcimBYiAAAAAILz6MHMNiMAOpe_B323MMMKJBsw"

if DEBUG:
    # Email ourselves so we can check when debugging.
    EMAIL_HOST = 'smtp.mailtrap.io'
    EMAIL_HOST_USER = '88f09b9a19d424'
    EMAIL_HOST_PASSWORD = '42fdd93b4636c1'
    EMAIL_PORT = 587
    EMAIL_USE_TLS = True

#import export settings
IMPORT_EXPORT_USE_TRANSACTIONS = True

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        # Include the default Django email handler for errors
        # This is what you'd get without configuring logging at all.
        'mail_admins': {
            'class': 'django.utils.log.AdminEmailHandler',
            'level': 'ERROR',
            # But the emails are plain text by default - HTML is nicer
            'include_html': True,
        },
        # Log to a text file that can be rotated by logrotate
        'logfile': {
            'class': 'logging.handlers.WatchedFileHandler',
            'filename': 'alllogs.log' if DEBUG else '/var/log/django/alllogs.log'
        },
    },
    'loggers': {
        # Again, default Django configuration to email unhandled exceptions
        'django.request': {
            'handlers': ['mail_admins'],
            'level': 'ERROR',
            'propagate': True,
        },
        # Might as well log any errors anywhere else in Django
        'django': {
            'handlers': ['logfile'],
            'level': 'ERROR',
            'propagate': False,
        },
        # Your own app - this assumes all your logger names start with "myapp."
        'myapp': {
            'handlers': ['logfile'],
            'level': 'WARNING',# Or maybe INFO or DEBUG
            'propagate': False
        },
    },
}

'''If you are runnig Django on Apache using mod_wsgi you have to add
WSGIPassAuthorization On
in your httpd.conf. Otherwise authorization header will be stripped out by mod_wsgi.'''
