# Generated by Django 4.2.7 on 2025-05-13 22:43

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('val', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nameFrom', models.CharField(max_length=255)),
                ('emailFrom', models.CharField(max_length=255)),
                ('replied', models.BooleanField(default=False)),
                ('content', models.TextField(max_length=1500)),
                ('isSDSDownload', models.BooleanField(default=False)),
                ('companyName', models.TextField(blank=True, max_length=1000, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MarketSector',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, max_length=500, null=True)),
                ('description', ckeditor.fields.RichTextField()),
                ('image', models.FileField(blank=True, null=True, upload_to='documents/')),
                ('product_feature_title', models.CharField(blank=True, max_length=100, null=True)),
                ('product_feature_desccription', models.CharField(blank=True, max_length=1000, null=True)),
                ('product_feature_image', models.FileField(blank=True, null=True, upload_to='documents/')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, max_length=500, null=True)),
                ('page', models.CharField(max_length=100)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('content', ckeditor.fields.RichTextField()),
                ('image', models.FileField(blank=True, null=True, upload_to='documents/')),
                ('linkURL', models.CharField(blank=True, max_length=1000, null=True)),
                ('linkText', models.CharField(blank=True, max_length=255, null=True)),
                ('linkColor', models.CharField(blank=True, help_text='Choose a color for the category menu. See <a href="https://www.w3schools.com/colors/colors_picker.asp">W3Schools Color Picker</a> for help choosing a color. If black (#000000) is chosen, a default color will be used.', max_length=7, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('subheading', models.CharField(blank=True, max_length=255, null=True)),
                ('secondaryImageLink', models.FileField(blank=True, null=True, upload_to='documents/')),
                ('primaryImageLink', models.FileField(blank=True, null=True, upload_to='documents/')),
                ('description', models.TextField(max_length=1000)),
                ('directions', models.TextField(max_length=2000)),
                ('productCode', models.CharField(max_length=255, unique=True)),
                ('productCodes', models.TextField(blank=True, max_length=1000, null=True)),
                ('brand', models.CharField(max_length=255)),
                ('infoSheet', models.FileField(blank=True, null=True, upload_to='documents/')),
                ('sdsSheet', models.FileField(blank=True, null=True, upload_to='documents/')),
                ('public', models.BooleanField(default=False)),
                ('usageType', models.CharField(blank=True, max_length=455)),
                ('amountDesc', models.CharField(blank=True, max_length=455)),
                ('properties', models.CharField(blank=True, help_text='Read only: Legacy field is no longer used. Exists only for reference.', max_length=500, null=True)),
                ('application', models.CharField(blank=True, help_text='Read only: Legacy field is no longer used. Exists only for reference.', max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('phoneNumber', models.CharField(max_length=100)),
                ('cellPhoneNumber', models.CharField(blank=True, max_length=100, null=True)),
                ('businessName', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=500)),
                ('profileType', models.CharField(blank=True, choices=[('customer', 'customer'), ('distributor', 'distributor'), ('admin', 'admin')], default='customer', max_length=255, null=True)),
                ('hasSetPassword', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SafetyWear',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('imageLink', models.CharField(max_length=455)),
            ],
        ),
        migrations.CreateModel(
            name='SectorSolution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, max_length=500, null=True)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('subtitle', models.CharField(blank=True, max_length=255, null=True)),
                ('content', models.TextField(blank=True, max_length=1000, null=True)),
                ('content_title', models.CharField(blank=True, max_length=255, null=True)),
                ('content_image', models.FileField(blank=True, null=True, upload_to='documents/')),
                ('content2_title', models.CharField(blank=True, max_length=255, null=True)),
                ('content2', models.TextField(blank=True, max_length=1000, null=True)),
                ('content2_image', models.FileField(blank=True, null=True, upload_to='documents/')),
                ('content3_title', models.CharField(blank=True, max_length=255, null=True)),
                ('content3', models.TextField(blank=True, max_length=1000, null=True)),
                ('footer_title', models.CharField(blank=True, max_length=255, null=True)),
                ('footer_subtitle', models.CharField(blank=True, max_length=255, null=True)),
                ('footer_image', models.FileField(blank=True, null=True, upload_to='documents/')),
                ('footer_subtitle2', models.CharField(blank=True, max_length=255, null=True)),
                ('extra', models.TextField(blank=True, max_length=1000, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('desc', models.CharField(max_length=255)),
                ('amount', models.CharField(max_length=255)),
                ('image', models.FileField(blank=True, null=True, upload_to='documents/')),
                ('imageNo', models.FileField(blank=True, null=True, upload_to='documents/')),
                ('isBag', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('profile_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='chemsapp.profile')),
                ('geocodingDetail', models.TextField(blank=True, max_length=1500, null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('chemsapp.profile',),
        ),
        migrations.CreateModel(
            name='Distributor',
            fields=[
                ('profile_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='chemsapp.profile')),
                ('geocodingDetail', models.TextField(blank=True, max_length=1500, null=True)),
                ('primaryImageLink', models.FileField(blank=True, null=True, upload_to='documents/')),
                ('customers', models.ManyToManyField(blank=True, null=True, related_name='distributors', to='chemsapp.customer')),
            ],
            options={
                'abstract': False,
            },
            bases=('chemsapp.profile',),
        ),
        migrations.CreateModel(
            name='NewsArticle',
            fields=[
                ('post_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='chemsapp.post')),
                ('postType', models.CharField(blank=True, max_length=100, null=True)),
                ('postDate', models.DateTimeField(auto_now_add=True)),
                ('isFeatured', models.BooleanField(default=False)),
                ('isActive', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
            bases=('chemsapp.post',),
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(max_length=1000)),
                ('image', models.FileField(blank=True, null=True, upload_to='documents/')),
                ('menu_color', models.CharField(blank=True, help_text='Choose a color for the category menu. See <a href="https://www.w3schools.com/colors/colors_picker.asp">W3Schools Color Picker</a> for help choosing a color. If black (#000000) is chosen, a default color will be used.', max_length=7, null=True)),
                ('isSubCategory', models.BooleanField(default=False)),
                ('products', models.ManyToManyField(blank=True, null=True, related_name='categories', to='chemsapp.product')),
                ('relatedCategory', models.ManyToManyField(blank=True, to='chemsapp.productcategory')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='productCategory',
            field=models.ManyToManyField(blank=True, null=True, related_name='categories', to='chemsapp.productcategory'),
        ),
        migrations.AddField(
            model_name='product',
            name='safetyWears',
            field=models.ManyToManyField(blank=True, related_name='products', to='chemsapp.safetywear'),
        ),
        migrations.AddField(
            model_name='product',
            name='sizes',
            field=models.ManyToManyField(blank=True, related_name='products', to='chemsapp.size'),
        ),
        migrations.AddField(
            model_name='product',
            name='subCategory',
            field=models.ManyToManyField(blank=True, null=True, related_name='subcategories', to='chemsapp.productcategory'),
        ),
        migrations.AddField(
            model_name='product',
            name='uploadedBy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products_added', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='MarketSectorSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, max_length=1000, null=True)),
                ('image', models.FileField(blank=True, null=True, upload_to='documents/')),
                ('sector', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='chemsapp.marketsector')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='marketsector',
            name='product_feature',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sectors', to='chemsapp.product'),
        ),
        migrations.CreateModel(
            name='MarketCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=500, null=True)),
                ('image', models.FileField(blank=True, null=True, upload_to='documents/')),
                ('products', models.ManyToManyField(blank=True, null=True, related_name='markets', to='chemsapp.product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductRemove',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productRemoved', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productsRemoves', to='chemsapp.product')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productRemoves', to='chemsapp.customer')),
                ('distributor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productRemoves', to='chemsapp.distributor')),
            ],
        ),
        migrations.CreateModel(
            name='ProductAdd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productAdded', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productsAdds', to='chemsapp.product')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productAdds', to='chemsapp.customer')),
                ('distributor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productAdds', to='chemsapp.distributor')),
            ],
        ),
        migrations.AddField(
            model_name='customer',
            name='distributorParent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='distributorParent', to='chemsapp.distributor'),
        ),
        migrations.AddField(
            model_name='customer',
            name='products',
            field=models.ManyToManyField(blank=True, null=True, related_name='customers', to='chemsapp.product'),
        ),
    ]
