# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-01 01:58
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MyBaseModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('archived', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('mybasemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='chemsapp.MyBaseModel')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('primaryImageLink', models.CharField(max_length=500)),
                ('secondaryImageLink', models.CharField(max_length=500)),
                ('usageType', models.CharField(max_length=455)),
                ('amountDesc', models.CharField(max_length=455)),
                ('instructions', models.TextField(max_length=2000)),
                ('productCode', models.CharField(max_length=255, unique=True)),
                ('brand', models.CharField(max_length=255)),
                ('infoSheetLink', models.CharField(max_length=255)),
                ('sdsSheetLink', models.CharField(max_length=255)),
            ],
            bases=('chemsapp.mybasemodel',),
        ),
        migrations.CreateModel(
            name='ProductAdd',
            fields=[
                ('mybasemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='chemsapp.MyBaseModel')),
                ('productAdded', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productsAdds', to='chemsapp.Product')),
            ],
            bases=('chemsapp.mybasemodel',),
        ),
        migrations.CreateModel(
            name='ProductRemove',
            fields=[
                ('mybasemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='chemsapp.MyBaseModel')),
                ('productRemoved', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productsRemoves', to='chemsapp.Product')),
            ],
            bases=('chemsapp.mybasemodel',),
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('mybasemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='chemsapp.MyBaseModel')),
                ('phone_number', models.CharField(max_length=100)),
                ('cell_phone_number', models.CharField(max_length=100)),
                ('business_name', models.CharField(max_length=255)),
                ('lat', models.DecimalField(decimal_places=8, max_digits=80)),
                ('lon', models.DecimalField(decimal_places=8, max_digits=80)),
            ],
            bases=('chemsapp.mybasemodel',),
        ),
        migrations.CreateModel(
            name='SafetyWear',
            fields=[
                ('mybasemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='chemsapp.MyBaseModel')),
                ('name', models.CharField(max_length=255)),
                ('imageLink', models.CharField(max_length=455)),
            ],
            bases=('chemsapp.mybasemodel',),
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('profile_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='chemsapp.Profile')),
            ],
            bases=('chemsapp.profile',),
        ),
        migrations.CreateModel(
            name='Distributor',
            fields=[
                ('profile_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='chemsapp.Profile')),
                ('customers', models.ManyToManyField(related_name='distributors', to='chemsapp.Customer')),
            ],
            bases=('chemsapp.profile',),
        ),
        migrations.AddField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='product',
            name='safetyWears',
            field=models.ManyToManyField(related_name='products', to='chemsapp.SafetyWear'),
        ),
        migrations.AddField(
            model_name='productremove',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productRemoves', to='chemsapp.Customer'),
        ),
        migrations.AddField(
            model_name='productremove',
            name='distributor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productRemoves', to='chemsapp.Distributor'),
        ),
        migrations.AddField(
            model_name='productadd',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productAdds', to='chemsapp.Customer'),
        ),
        migrations.AddField(
            model_name='productadd',
            name='distributor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productAdds', to='chemsapp.Distributor'),
        ),
        migrations.AddField(
            model_name='customer',
            name='products',
            field=models.ManyToManyField(related_name='customers', to='chemsapp.Product'),
        ),
    ]
