# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-08 20:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chemsapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='infosheet',
            name='productRelated',
        ),
        migrations.RemoveField(
            model_name='sdssheet',
            name='productRelatedTo',
        ),
        migrations.RemoveField(
            model_name='product',
            name='infoSheetLink',
        ),
        migrations.RemoveField(
            model_name='product',
            name='sdsSheetLink',
        ),
        migrations.AddField(
            model_name='product',
            name='infoSheet',
            field=models.FileField(null=True, upload_to='documents/'),
        ),
        migrations.AddField(
            model_name='product',
            name='sdsSheet',
            field=models.FileField(null=True, upload_to='documents/'),
        ),
        migrations.DeleteModel(
            name='InfoSheet',
        ),
        migrations.DeleteModel(
            name='SDSSheet',
        ),
    ]
