# Generated by Django 4.2.7 on 2025-10-17 21:40

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chemsapp', '0002_post_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='directions',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
