# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-08 20:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chemsapp', '0002_auto_20171208_2006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='products',
            field=models.ManyToManyField(null=True, related_name='customers', to='chemsapp.Product'),
        ),
        migrations.AlterField(
            model_name='distributor',
            name='customers',
            field=models.ManyToManyField(null=True, related_name='distributors', to='chemsapp.Customer'),
        ),
    ]
