# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-04 04:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chemsapp', '0002_mybasemodel_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mybasemodel',
            name='created_by',
        ),
        migrations.AddField(
            model_name='product',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='chemsapp.Profile', unique=True),
        ),
    ]
