# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-04 04:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chemsapp', '0003_auto_20171204_0403'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='created_by',
        ),
    ]
