# Generated by Django 4.2.7 on 2026-01-09 03:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def migrate_distributor_data_forward(apps, schema_editor):
    """
    Migrate data from the old Profile-based Distributor to the new standalone Distributor
    """
    # Get the old Profile model (with distributor subclass data)
    Profile = apps.get_model('chemsapp', 'Profile')
    # We'll create records in the new distributor table manually via SQL
    # because Django doesn't know about the new model structure yet

    db_alias = schema_editor.connection.alias
    cursor = schema_editor.connection.cursor()

    # Check if the old distributor table exists
    cursor.execute("""
        SELECT EXISTS (
            SELECT FROM information_schema.tables
            WHERE table_schema = 'public'
            AND table_name = 'chemsapp_distributor_old'
        );
    """)
    table_exists = cursor.fetchone()[0]

    if not table_exists:
        # No old table to migrate from, skip data migration
        return

    # Find all distributor profiles
    distributors = Profile.objects.using(db_alias).filter(profileType='distributor')

    for dist_profile in distributors:
        # Get the old distributor record (if exists) - note: using _old suffix
        cursor.execute(
            'SELECT "geocodingDetail", "primaryImageLink" FROM chemsapp_distributor_old WHERE profile_ptr_id = %s',
            [dist_profile.id]
        )
        old_dist_data = cursor.fetchone()

        if old_dist_data:
            geocoding_detail = old_dist_data[0] or ''
            primary_image = old_dist_data[1] or ''
        else:
            geocoding_detail = ''
            primary_image = ''

        # Insert into new distributor table
        cursor.execute(
            """INSERT INTO chemsapp_distributor_new
               (phonenumber, cellphonenumber, businessname, address, profiletype,
                hassetpassword, geocodingdetail, primaryimagelink, created_at, updated_at)
               VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s)
               RETURNING id""",
            [
                dist_profile.phoneNumber,
                dist_profile.cellPhoneNumber,
                dist_profile.businessName,
                dist_profile.address,
                'distributor',
                dist_profile.hasSetPassword,
                geocoding_detail,
                primary_image,
                dist_profile.created_at,
                dist_profile.updated_at
            ]
        )
        new_dist_id = cursor.fetchone()[0]

        # Migrate the user relationship to the new ManyToMany table
        cursor.execute(
            """INSERT INTO chemsapp_distributor_new_users (distributor_id, user_id)
               VALUES (%s, %s)""",
            [new_dist_id, dist_profile.user_id]
        )

        # Migrate customer relationships if they exist
        if old_dist_data:
            cursor.execute(
                """SELECT customer_id FROM chemsapp_distributor_customers_old
                   WHERE distributor_id = %s""",
                [dist_profile.id]
            )
            customer_ids = cursor.fetchall()
            for (customer_id,) in customer_ids:
                cursor.execute(
                    """INSERT INTO chemsapp_distributor_new_customers (distributor_id, customer_id)
                       VALUES (%s, %s)""",
                    [new_dist_id, customer_id]
                )


def migrate_distributor_data_backward(apps, schema_editor):
    """
    Reverse migration - not implementing for safety
    """
    pass


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chemsapp', '0003_alter_product_description_alter_product_directions'),
    ]

    operations = [
        # Step 1: Rename old distributor table to temporary name (if exists)
        migrations.RunSQL(
            """
            DO $$
            BEGIN
                IF EXISTS (SELECT FROM information_schema.tables
                          WHERE table_schema = 'public'
                          AND table_name = 'chemsapp_distributor') THEN
                    ALTER TABLE chemsapp_distributor RENAME TO chemsapp_distributor_old;
                END IF;
            END $$;
            """,
            reverse_sql="ALTER TABLE chemsapp_distributor_old RENAME TO chemsapp_distributor;"
        ),
        migrations.RunSQL(
            """
            DO $$
            BEGIN
                IF EXISTS (SELECT FROM information_schema.tables
                          WHERE table_schema = 'public'
                          AND table_name = 'chemsapp_distributor_customers') THEN
                    ALTER TABLE chemsapp_distributor_customers RENAME TO chemsapp_distributor_customers_old;
                END IF;
            END $$;
            """,
            reverse_sql="ALTER TABLE chemsapp_distributor_customers_old RENAME TO chemsapp_distributor_customers;"
        ),

        # Step 2: Create new standalone Distributor table
        migrations.RunSQL(
            """CREATE TABLE chemsapp_distributor_new (
                id SERIAL PRIMARY KEY,
                phonenumber VARCHAR(100) NOT NULL DEFAULT '',
                cellphonenumber VARCHAR(100),
                businessname VARCHAR(255) NOT NULL DEFAULT '',
                address VARCHAR(500) NOT NULL DEFAULT '',
                profiletype VARCHAR(255) DEFAULT 'distributor',
                hassetpassword BOOLEAN NOT NULL DEFAULT false,
                geocodingdetail TEXT,
                primaryimagelink VARCHAR(100),
                created_at TIMESTAMP NOT NULL,
                updated_at TIMESTAMP NOT NULL
            );""",
            reverse_sql="DROP TABLE chemsapp_distributor_new;"
        ),

        # Step 3: Create ManyToMany table for users
        migrations.RunSQL(
            """CREATE TABLE chemsapp_distributor_new_users (
                id SERIAL PRIMARY KEY,
                distributor_id INTEGER NOT NULL,
                user_id INTEGER NOT NULL,
                CONSTRAINT fk_distributor FOREIGN KEY (distributor_id) REFERENCES chemsapp_distributor_new(id) ON DELETE CASCADE,
                CONSTRAINT fk_user FOREIGN KEY (user_id) REFERENCES auth_user(id) ON DELETE CASCADE,
                CONSTRAINT unique_distributor_user UNIQUE (distributor_id, user_id)
            );""",
            reverse_sql="DROP TABLE chemsapp_distributor_new_users;"
        ),

        # Step 4: Create ManyToMany table for customers
        migrations.RunSQL(
            """CREATE TABLE chemsapp_distributor_new_customers (
                id SERIAL PRIMARY KEY,
                distributor_id INTEGER NOT NULL,
                customer_id INTEGER NOT NULL,
                CONSTRAINT fk_dist_customer FOREIGN KEY (distributor_id) REFERENCES chemsapp_distributor_new(id) ON DELETE CASCADE,
                CONSTRAINT fk_customer FOREIGN KEY (customer_id) REFERENCES chemsapp_customer(profile_ptr_id) ON DELETE CASCADE,
                CONSTRAINT unique_distributor_customer UNIQUE (distributor_id, customer_id)
            );""",
            reverse_sql="DROP TABLE chemsapp_distributor_new_customers;"
        ),

        # Step 5: Migrate data
        migrations.RunPython(
            migrate_distributor_data_forward,
            migrate_distributor_data_backward
        ),

        # Step 6: Rename new table to final name
        migrations.RunSQL(
            "ALTER TABLE chemsapp_distributor_new RENAME TO chemsapp_distributor;",
            reverse_sql="ALTER TABLE chemsapp_distributor RENAME TO chemsapp_distributor_new;"
        ),
        migrations.RunSQL(
            "ALTER TABLE chemsapp_distributor_new_users RENAME TO chemsapp_distributor_users;",
            reverse_sql="ALTER TABLE chemsapp_distributor_users RENAME TO chemsapp_distributor_new_users;"
        ),
        migrations.RunSQL(
            "ALTER TABLE chemsapp_distributor_new_customers RENAME TO chemsapp_distributor_customers;",
            reverse_sql="ALTER TABLE chemsapp_distributor_customers RENAME TO chemsapp_distributor_new_customers;"
        ),

        # Step 7: Clean up old tables
        migrations.RunSQL(
            "DROP TABLE IF EXISTS chemsapp_distributor_old CASCADE;",
            reverse_sql=migrations.RunSQL.noop
        ),
        migrations.RunSQL(
            "DROP TABLE IF EXISTS chemsapp_distributor_customers_old CASCADE;",
            reverse_sql=migrations.RunSQL.noop
        ),
    ]
