# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-09 21:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chemsapp', '0003_auto_20171208_2009'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='geocodingDetail',
            field=models.TextField(null=True),
        ),
    ]
