# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-05 01:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chemsapp', '0004_remove_product_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profileType',
            field=models.CharField(choices=[('customer', 'customer'), ('distributor', 'distributor'), ('admin', 'admin')], default='customer', max_length=255, null=True),
        ),
    ]
