# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-06 04:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chemsapp', '0005_profile_profiletype'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='business_name',
            new_name='businessName',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='cell_phone_number',
            new_name='cellPhoneNumber',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='phone_number',
            new_name='phoneNumber',
        ),
        migrations.AddField(
            model_name='profile',
            name='hasSetPassword',
            field=models.BooleanField(default=False),
        ),
    ]
