# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-10 00:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chemsapp', '0005_auto_20171210_0024'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='geocodingDetail',
        ),
        migrations.AddField(
            model_name='customer',
            name='geocodingDetail',
            field=models.TextField(max_length=1500, null=True),
        ),
        migrations.AddField(
            model_name='distributor',
            name='geocodingDetail',
            field=models.TextField(max_length=1500, null=True),
        ),
    ]
