# Generated by Django 4.2.7 on 2026-01-09 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chemsapp', '0005_sync_distributor_model_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='products',
            field=models.ManyToManyField(blank=True, related_name='customers', to='chemsapp.product'),
        ),
        migrations.AlterField(
            model_name='distributor',
            name='customers',
            field=models.ManyToManyField(blank=True, related_name='distributors', to='chemsapp.customer'),
        ),
        migrations.AlterField(
            model_name='marketcategory',
            name='products',
            field=models.ManyToManyField(blank=True, related_name='markets', to='chemsapp.product'),
        ),
        migrations.AlterField(
            model_name='product',
            name='productCategory',
            field=models.ManyToManyField(blank=True, related_name='categories', to='chemsapp.productcategory'),
        ),
        migrations.AlterField(
            model_name='product',
            name='subCategory',
            field=models.ManyToManyField(blank=True, related_name='subcategories', to='chemsapp.productcategory'),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='products',
            field=models.ManyToManyField(blank=True, related_name='categories', to='chemsapp.product'),
        ),
    ]
