# Generated by Django 4.2.7 on 2026-01-09 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chemsapp', '0006_alter_customer_products_alter_distributor_customers_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='distributorParent',
        ),
    ]
