# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-10 00:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chemsapp', '0006_auto_20171210_0025'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='lat',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='lon',
        ),
    ]
