# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-13 22:56
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chemsapp', '0007_auto_20171210_0032'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='uploadedBy',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='products_added', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
