# Generated by Django 4.2.7 on 2026-03-12 23:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chemsapp', '0007_remove_customer_distributorparent'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pack_size', models.IntegerField()),
                ('description', models.TextField(blank=True, null=True)),
                ('barcode', models.CharField(max_length=255)),
                ('image', models.FileField(blank=True, null=True, upload_to='documents/')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='chemsapp.product')),
                ('size', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='variants', to='chemsapp.size')),
            ],
        ),
    ]
