# Generated by Django 4.2.7 on 2026-03-13 00:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chemsapp', '0008_productvariant'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerProductVariant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_stock_level', models.IntegerField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_variants', to='chemsapp.customer')),
                ('product_variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_variants', to='chemsapp.productvariant')),
            ],
        ),
    ]
