# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-31 06:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chemsapp', '0009_auto_20171231_0511'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='distributorParent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='chemsapp.Distributor'),
        ),
    ]
