# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-05 20:06
from __future__ import unicode_literals

import chemsapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chemsapp', '0011_auto_20180305_1956'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, unique=True)),
                ('page', models.CharField(max_length=100)),
                ('content', models.TextField(blank=True, max_length=2000, null=True)),
                ('image', models.FileField(blank=True, null=True, upload_to='documents/')),
            ],
            bases=(chemsapp.models.MyBaseModel, models.Model),
        ),
    ]
