# Generated by Django 4.2.7 on 2026-03-13 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chemsapp', '0011_productvariant_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='customercontact',
            name='role',
            field=models.CharField(default='', max_length=255),
        ),
    ]
