# Generated by Django 4.2.7 on 2026-05-09 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chemsapp', '0012_customercontact_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='wall_chart_color',
            field=models.CharField(blank=True, help_text='Background colour for this product on wall chart PDFs. See <a href="https://www.w3schools.com/colors/colors_picker.asp">W3Schools Color Picker</a>. Leave blank for white.', max_length=7, null=True),
        ),
    ]
