# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-05 21:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chemsapp', '0012_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='subCategory',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
