# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-05 21:10
from __future__ import unicode_literals

import chemsapp.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chemsapp', '0013_product_subcategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            bases=(chemsapp.models.MyBaseModel, models.Model),
        ),
        migrations.AddField(
            model_name='product',
            name='productCategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='chemsapp.ProductCategory'),
        ),
    ]
