# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-05 21:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.datetime_safe


class Migration(migrations.Migration):

    dependencies = [
        ('chemsapp', '0014_auto_20180305_2110'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcategory',
            name='description',
            field=models.TextField(default=django.utils.datetime_safe.datetime.now, max_length=1000),
            preserve_default=False,
        ),
    ]
