# Generated by Django 4.2.7 on 2026-05-16 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chemsapp', '0015_set_random_wall_chart_colors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='application',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='properties',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='safetywear',
            name='imageLink',
            field=models.FileField(blank=True, null=True, upload_to='icons/'),
        ),
    ]
