# Generated by Django 4.2.7 on 2026-06-22 10:16

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chemsapp', '0016_safetywear_imagefield'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='procedure',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='application',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
