# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-16 22:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chemsapp', '0016_auto_20180316_1033'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='marketingDesc',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
