# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-19 04:44
from __future__ import unicode_literals

import chemsapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chemsapp', '0017_product_marketingdesc'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=500, null=True)),
                ('image', models.FileField(blank=True, null=True, upload_to='documents/')),
            ],
            bases=(chemsapp.models.MyBaseModel, models.Model),
        ),
        migrations.RemoveField(
            model_name='product',
            name='market',
        ),
        migrations.RemoveField(
            model_name='product',
            name='marketingDesc',
        ),
        migrations.AddField(
            model_name='product',
            name='application',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='properties',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='marketcategory',
            name='products',
            field=models.ManyToManyField(blank=True, null=True, related_name='markets', to='chemsapp.Product'),
        ),
    ]
