# Generated by Django 4.2.7 on 2026-07-26 04:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chemsapp', '0017_product_procedure_alter_product_application'),
    ]

    operations = [
        migrations.CreateModel(
            name='FillType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('volume_litres', models.DecimalField(decimal_places=3, max_digits=8)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='product',
            name='dilution_ratio',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Dilution 1:X — enter 100 for 1:100. Leave blank for ready-to-use/non-liquid products.', max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='volume_litres',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Container volume in litres used for cost-in-use maths. Do not rely on Size.amount.', max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='fill_types',
            field=models.ManyToManyField(blank=True, help_text='Fill/container types shown as "Cost in use" lines on quote proposals.', related_name='products', to='chemsapp.filltype'),
        ),
        migrations.CreateModel(
            name='VariantFillOverride',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fills', models.DecimalField(decimal_places=2, help_text='Number of fills per unit; cost in use = price ÷ fills', max_digits=10)),
                ('fill_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variant_overrides', to='chemsapp.filltype')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fill_overrides', to='chemsapp.productvariant')),
            ],
            options={
                'unique_together': {('variant', 'fill_type')},
            },
        ),
    ]
