# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-28 23:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chemsapp', '0018_auto_20180319_0444'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='productCategory',
        ),
        migrations.AddField(
            model_name='product',
            name='productCategory',
            field=models.ManyToManyField(blank=True, null=True, related_name='products', to='chemsapp.ProductCategory'),
        ),
    ]
