# Generated by Django 4.2.7 on 2026-07-26 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chemsapp', '0018_filltype_product_dilution_ratio_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productvariant',
            name='volume_litres',
        ),
        migrations.AddField(
            model_name='size',
            name='volume_litres',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='Container volume in litres used for cost-in-use maths. The free-text "amount" field is not used for calculations.', max_digits=8, null=True),
        ),
    ]
