# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-29 00:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chemsapp', '0019_auto_20180328_2359'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcategory',
            name='products',
            field=models.ManyToManyField(blank=True, null=True, related_name='categories', to='chemsapp.Product'),
        ),
        migrations.AlterField(
            model_name='product',
            name='productCategory',
            field=models.ManyToManyField(blank=True, null=True, related_name='categories', to='chemsapp.ProductCategory'),
        ),
    ]
