# Generated by Django 4.2.7 on 2026-08-02 07:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chemsapp', '0019_remove_productvariant_volume_litres_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('category', models.CharField(blank=True, default='', help_text='Grouping shown in the quote builder, e.g. "Spray Bottle", "Sanitising".', max_length=100)),
                ('value_kind', models.CharField(choices=[('ratio', 'Dilution ratio (water:chemical, 0 = undiluted)'), ('ml_per_litre', 'ml per litre'), ('g_per_litre', 'grams per litre'), ('ml_per_kg', 'ml per kg'), ('g_per_kg', 'grams per kg'), ('ml_per_cycle', 'ml per cycle'), ('g_per_cycle', 'grams per cycle')], default='ratio', max_length=20)),
                ('unit_volume_litres', models.DecimalField(blank=True, decimal_places=3, help_text='Container/basis volume for ratio kinds, e.g. 0.75 for a spray bottle. Blank for per-cycle/per-kg kinds.', max_digits=8, null=True)),
                ('unit_label', models.CharField(help_text='Cost-in-use unit shown on proposals, e.g. "per 750ml spray bottle", "per cycle".', max_length=100)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='DilutionVariant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(blank=True, decimal_places=2, help_text='Ratio or dose per the application type; 0 = undiluted/ready to use. Blank when only the note applies.', max_digits=8, null=True)),
                ('note', models.CharField(blank=True, default='', help_text='e.g. "Check manufacturer\'s recommendation"', max_length=255)),
                ('application_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dilutions', to='chemsapp.applicationtype')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dilutions', to='chemsapp.productvariant')),
            ],
            options={
                'ordering': ['application_type__sort_order', 'application_type__name'],
                'unique_together': {('variant', 'application_type')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='variantfilloverride',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='variantfilloverride',
            name='fill_type',
        ),
        migrations.RemoveField(
            model_name='variantfilloverride',
            name='variant',
        ),
        migrations.RemoveField(
            model_name='product',
            name='dilution_ratio',
        ),
        migrations.RemoveField(
            model_name='product',
            name='fill_types',
        ),
        migrations.DeleteModel(
            name='FillType',
        ),
        migrations.DeleteModel(
            name='VariantFillOverride',
        ),
    ]
