# Generated by Django 4.2.7 on 2026-08-30 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chemsapp', '0020_applicationtype_dilutionvariant_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='recommended_retail_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Recommended retail price, in dollars.', max_digits=10, null=True),
        ),
    ]
