# Generated by Django 4.2.7 on 2026-08-30 05:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chemsapp', '0021_product_recommended_retail_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='PricingVariant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, help_text='Price that these customers pay for this product, in dollars.', max_digits=10)),
                ('name', models.CharField(blank=True, default='', help_text='Optional label, e.g. "2026 contract" or "Bulk tier".', max_length=255)),
                ('customers', models.ManyToManyField(blank=True, related_name='pricing_variants', to='chemsapp.customer')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pricing_variants', to='chemsapp.product')),
            ],
            options={
                'ordering': ['product__name', 'price'],
            },
        ),
    ]
