# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-03 16:12
from __future__ import unicode_literals

import chemsapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chemsapp', '0021_productcategory_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('val', models.CharField(max_length=255)),
            ],
            bases=(chemsapp.models.MyBaseModel, models.Model),
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameFrom', models.CharField(max_length=255)),
                ('emailFrom', models.CharField(max_length=255)),
                ('replied', models.BooleanField(default=False)),
                ('content', models.TextField(max_length=1500)),
            ],
            bases=(chemsapp.models.MyBaseModel, models.Model),
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('desc', models.CharField(max_length=255)),
                ('amount', models.CharField(max_length=255)),
            ],
            bases=(chemsapp.models.MyBaseModel, models.Model),
        ),
    ]
