# Generated by Django 4.2.7 on 2026-08-30 06:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chemsapp', '0022_pricingvariant'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricingvariant',
            name='min_quantity',
            field=models.PositiveIntegerField(blank=True, help_text='Smallest order that gets this price. Blank for any quantity.', null=True, verbose_name='Minimum quantity'),
        ),
        migrations.AddField(
            model_name='product',
            name='application_sheet',
            field=models.FileField(blank=True, help_text='Product application sheet.', null=True, upload_to='documents/'),
        ),
        migrations.AddField(
            model_name='product',
            name='bom',
            field=models.TextField(blank=True, default='', help_text='Bill of materials for this product.', verbose_name='BOM'),
        ),
        migrations.AddField(
            model_name='product',
            name='mpi_approval',
            field=models.CharField(blank=True, default='', help_text='MPI approval number, e.g. "C32".', max_length=255, verbose_name='MPI approval'),
        ),
        migrations.AddField(
            model_name='product',
            name='mpi_approval_sheet',
            field=models.FileField(blank=True, null=True, upload_to='documents/', verbose_name='MPI approval document'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_range',
            field=models.CharField(blank=True, default='', help_text='Range within the brand, e.g. "Professional".', max_length=255),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='carton_barcode',
            field=models.CharField(blank=True, default='', help_text='Barcode of the carton, when it differs from the unit barcode.', max_length=255),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='label',
            field=models.FileField(blank=True, help_text='Product label artwork for this size.', null=True, upload_to='documents/'),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='label_code',
            field=models.CharField(blank=True, default='', help_text='Label code, e.g. "LABCLEANG05".', max_length=255),
        ),
        migrations.CreateModel(
            name='ProductEquivalency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.CharField(blank=True, default='', help_text='e.g. "Same dilution" or "Use 20% more".', max_length=255)),
                ('equivalent_product', models.ForeignKey(help_text='The product that this one replaces, or is replaced by.', on_delete=django.db.models.deletion.CASCADE, related_name='equivalent_to', to='chemsapp.product')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equivalents', to='chemsapp.product')),
            ],
            options={
                'verbose_name_plural': 'Product equivalencies',
                'ordering': ['equivalent_product__name'],
                'unique_together': {('product', 'equivalent_product')},
            },
        ),
    ]
