# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-10 22:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chemsapp', '0022_config_contact_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sizes',
            field=models.ManyToManyField(blank=True, related_name='products', to='chemsapp.Size'),
        ),
        migrations.AddField(
            model_name='size',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='documents/'),
        ),
    ]
