# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-12 12:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chemsapp', '0023_auto_20180410_2258'),
    ]

    operations = [
        migrations.AddField(
            model_name='size',
            name='imageNo',
            field=models.FileField(blank=True, null=True, upload_to='documents/'),
        ),
    ]
