# Generated by Django 4.2.7 on 2026-09-05 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chemsapp', '0023_pricingvariant_min_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='recommended_retail_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Recommended retail price of this size, in dollars.', max_digits=10, null=True),
        ),
    ]
