# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-13 08:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chemsapp', '0024_size_imageno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='distributor',
            name='primaryImageLink',
            field=models.FileField(blank=True, null=True, upload_to='documents/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='primaryImageLink',
            field=models.FileField(blank=True, null=True, upload_to='documents/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='secondaryImageLink',
            field=models.FileField(blank=True, null=True, upload_to='documents/'),
        ),
    ]
