# Generated by Django 4.2.7 on 2026-09-08 20:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chemsapp', '0026_pricing_moves_to_variant'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('note', models.CharField(blank=True, default='', max_length=500)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='customer',
            name='group',
            field=models.ForeignKey(blank=True, help_text='The one group this customer is in. Blank for no group.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customers', to='chemsapp.customergroup'),
        ),
    ]
