# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-26 21:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chemsapp', '0026_auto_20180426_2056'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcategory',
            name='isSubCategory',
            field=models.BooleanField(default=False),
        ),
    ]
