# Generated by Django 4.2.7 on 2026-09-10 23:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chemsapp', '0027_customergroup_customer_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupPricingVariant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, help_text='Price that this group pays for this variant, in dollars.', max_digits=10)),
                ('name', models.CharField(blank=True, default='', help_text='Optional label, e.g. "2026 contract".', max_length=255)),
                ('min_quantity', models.PositiveIntegerField(blank=True, help_text='Smallest order that gets this price. Blank for any quantity.', null=True, verbose_name='Minimum quantity')),
                ('customer_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pricing_variants', to='chemsapp.customergroup')),
                ('product_variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_pricing_variants', to='chemsapp.productvariant')),
            ],
            options={
                'ordering': ['product_variant__product__name', 'product_variant__code', 'price'],
            },
        ),
        migrations.AddConstraint(
            model_name='grouppricingvariant',
            constraint=models.UniqueConstraint(fields=('product_variant', 'customer_group'), name='one_group_price_per_variant_and_group'),
        ),
    ]
