# Generated by Django 4.2.7 on 2026-09-20 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chemsapp', '0028_grouppricingvariant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='distributor',
            name='profiletype',
            field=models.CharField(blank=True, choices=[('customer', 'customer'), ('distributor', 'distributor'), ('admin', 'admin'), ('applead', 'applead')], default='distributor', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profileType',
            field=models.CharField(blank=True, choices=[('customer', 'customer'), ('distributor', 'distributor'), ('admin', 'admin'), ('applead', 'applead')], default='customer', max_length=255, null=True),
        ),
    ]
