# Generated by Django 4.2.7 on 2026-09-20 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chemsapp', '0029_alter_distributor_profiletype_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppLeadSignupCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('email', models.EmailField(max_length=254)),
                ('password_hash', models.CharField(max_length=255)),
                ('first_name', models.CharField(blank=True, default='', max_length=255)),
                ('last_name', models.CharField(blank=True, default='', max_length=255)),
                ('business_name', models.CharField(blank=True, default='', max_length=255)),
                ('code', models.CharField(max_length=6)),
                ('expires_at', models.DateTimeField()),
                ('consumed', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
