# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-04-28 23:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chemsapp', '0030_size_isbag'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcategory',
            name='relatedCategory',
            field=models.ManyToManyField(to='chemsapp.ProductCategory'),
        ),
    ]
