# Generated by Django 4.2.7 on 2026-09-20 09:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chemsapp', '0030_appleadsignupcode'),
    ]

    operations = [
        migrations.CreateModel(
            name='GellerAISyncRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('include_pdfs', models.BooleanField(default=False)),
                ('total', models.IntegerField(default=0)),
                ('processed', models.IntegerField(default=0)),
                ('succeeded', models.IntegerField(default=0)),
                ('failed', models.IntegerField(default=0)),
                ('errors', models.JSONField(blank=True, default=list)),
                ('done', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
