# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2020-05-20 05:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chemsapp', '0032_auto_20200520_0525'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='productCodes',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
