# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2020-05-20 06:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chemsapp', '0033_product_productcodes'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='linkText',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='linkURL',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
