# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2020-05-27 04:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chemsapp', '0034_auto_20200520_0630'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='subheading',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
