# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2020-05-27 04:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chemsapp', '0035_productcategory_menu_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcategory',
            name='relatedCategory',
            field=models.ManyToManyField(blank=True, to='chemsapp.ProductCategory'),
        ),
    ]
