# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2020-05-27 05:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chemsapp', '0035_product_subheading'),
        ('chemsapp', '0036_auto_20200527_0450'),
    ]

    operations = [
    ]
