# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2020-06-10 04:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chemsapp', '0037_merge_20200527_0509'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='companyName',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='isSDSDownload',
            field=models.BooleanField(default=False),
        ),
    ]
