# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2020-06-11 02:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chemsapp', '0038_auto_20200610_0416'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='instructions',
            new_name='directions',
        ),
    ]
