# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2020-06-11 03:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chemsapp', '0039_auto_20200611_0259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='application',
            field=models.CharField(blank=True, help_text='Read only: Legacy field is no longer used. Exists only for reference.', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='properties',
            field=models.CharField(blank=True, help_text='Read only: Legacy field is no longer used. Exists only for reference.', max_length=500, null=True),
        ),
    ]
