# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2020-06-11 04:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chemsapp', '0040_auto_20200611_0336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(default='Please contact us to get a copy of our Product Information Sheet', max_length=1000),
            preserve_default=False,
        ),
    ]
