# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2020-06-11 04:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chemsapp', '0041_auto_20200611_0400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='amountDesc',
            field=models.CharField(blank=True, max_length=455),
        ),
        migrations.AlterField(
            model_name='product',
            name='usageType',
            field=models.CharField(blank=True, max_length=455),
        ),
    ]
