# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2020-06-14 23:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chemsapp', '0042_auto_20200611_0406'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='linkColor',
            field=models.CharField(blank=True, help_text='Choose a color for the category menu. See <a href="https://www.w3schools.com/colors/colors_picker.asp">W3Schools Color Picker</a> for help choosing a color. If black (#000000) is chosen, a default color will be used.', max_length=7, null=True),
        ),
    ]
