# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2022-09-13 21:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chemsapp', '0044_auto_20220906_0038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='cellPhoneNumber',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
