# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2025-04-12 04:41
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chemsapp', '0045_auto_20220913_2120'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsPost',
            fields=[
                ('post_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='chemsapp.Post')),
                ('postType', models.CharField(blank=True, max_length=100, null=True)),
                ('postDate', models.DateTimeField(auto_now_add=True)),
                ('isFeatured', models.BooleanField(default=False)),
                ('isActive', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
            bases=('chemsapp.post',),
        ),
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, max_length=500, null=True)),
                ('image', models.FileField(blank=True, null=True, upload_to=b'documents/')),
                ('description', ckeditor.fields.RichTextField()),
                ('product_feature', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sectors', to='chemsapp.Product')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
