# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2025-04-12 05:21
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chemsapp', '0046_newspost_sector'),
    ]

    operations = [
        migrations.AddField(
            model_name='sector',
            name='product_feature_desccription',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='sector',
            name='product_feature_image',
            field=models.FileField(blank=True, null=True, upload_to=b'documents/'),
        ),
        migrations.AddField(
            model_name='sector',
            name='product_feature_title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=ckeditor.fields.RichTextField(default=''),
            preserve_default=False,
        ),
    ]
