# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2025-04-12 06:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chemsapp', '0047_auto_20250412_0521'),
    ]

    operations = [
        migrations.AddField(
            model_name='sector',
            name='news_post_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sectors', to='chemsapp.NewsPost'),
        ),
        migrations.AddField(
            model_name='sector',
            name='news_post_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sectors_2', to='chemsapp.NewsPost'),
        ),
    ]
