# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2025-04-20 22:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chemsapp', '0048_auto_20250412_0636'),
    ]

    operations = [
        migrations.CreateModel(
            name='SectorSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, max_length=1000, null=True)),
                ('image', models.FileField(blank=True, null=True, upload_to=b'documents/')),
                ('sector', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='chemsapp.Sector')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Solution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, max_length=500, null=True)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('subtitle', models.CharField(blank=True, max_length=255, null=True)),
                ('content', models.TextField(blank=True, max_length=1000, null=True)),
                ('content_title', models.CharField(blank=True, max_length=255, null=True)),
                ('content_image', models.FileField(blank=True, null=True, upload_to=b'documents/')),
                ('content2_title', models.CharField(blank=True, max_length=255, null=True)),
                ('content2', models.TextField(blank=True, max_length=1000, null=True)),
                ('content2_image', models.FileField(blank=True, null=True, upload_to=b'documents/')),
                ('content3_title', models.CharField(blank=True, max_length=255, null=True)),
                ('content3', models.TextField(blank=True, max_length=1000, null=True)),
                ('footer_title', models.CharField(blank=True, max_length=255, null=True)),
                ('footer_subtitle', models.CharField(blank=True, max_length=255, null=True)),
                ('footer_image', models.FileField(blank=True, null=True, upload_to=b'documents/')),
                ('footer_subtitle2', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
