# Generated by Django 5.2 on 2025-04-24 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chemsapp', '0049_sectorsection_solution'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sector',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='documents/'),
        ),
        migrations.AlterField(
            model_name='sector',
            name='product_feature_image',
            field=models.FileField(blank=True, null=True, upload_to='documents/'),
        ),
        migrations.AlterField(
            model_name='sectorsection',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='documents/'),
        ),
        migrations.AlterField(
            model_name='solution',
            name='content2_image',
            field=models.FileField(blank=True, null=True, upload_to='documents/'),
        ),
        migrations.AlterField(
            model_name='solution',
            name='content_image',
            field=models.FileField(blank=True, null=True, upload_to='documents/'),
        ),
        migrations.AlterField(
            model_name='solution',
            name='footer_image',
            field=models.FileField(blank=True, null=True, upload_to='documents/'),
        ),
    ]
