# Generated by Django 4.2.7 on 2025-07-06 04:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('question_text', models.TextField()),
                ('question_type', models.CharField(choices=[('text', 'Text Input'), ('textarea', 'Long Text'), ('select', 'Select Dropdown'), ('radio', 'Multiple Choice (Radio)'), ('checkbox', 'Multiple Choice (Checkbox)'), ('yesno', 'Yes/No'), ('file', 'File Upload'), ('signature', 'Digital Signature'), ('date', 'Date'), ('number', 'Number'), ('client_select', 'Client Select')], max_length=20)),
                ('help_text', models.TextField(blank=True, null=True)),
                ('is_required', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('show_when_parent_value', models.CharField(blank=True, help_text='Show this question when parent has this value', max_length=255, null=True)),
                ('parent_question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child_questions', to='reports.question')),
            ],
            options={
                'ordering': ['order', 'question_text'],
            },
        ),
        migrations.CreateModel(
            name='ReportType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('auto_number_prefix', models.CharField(blank=True, help_text='Prefix for auto-generated document numbers', max_length=10, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ReportSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('report_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='reports.reporttype')),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document_number', models.CharField(max_length=50, unique=True)),
                ('store_compliance_manager', models.CharField(blank=True, max_length=255, null=True)),
                ('inspection_date', models.DateField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='draft', max_length=20)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='chemsapp.customer')),
                ('distributor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='chemsapp.distributor')),
                ('prepared_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports_prepared', to=settings.AUTH_USER_MODEL)),
                ('report_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='reports.reporttype')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports_reviewed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='QuestionOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('text', models.CharField(max_length=255)),
                ('value', models.CharField(max_length=255)),
                ('is_flag', models.BooleanField(default=False, help_text='Mark this option as requiring attention')),
                ('additional_instructions', models.TextField(blank=True, null=True)),
                ('attached_pdf', models.FileField(blank=True, null=True, upload_to='report_attachments/')),
                ('order', models.PositiveIntegerField(default=0)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='reports.question')),
            ],
            options={
                'ordering': ['order', 'text'],
            },
        ),
        migrations.AddField(
            model_name='question',
            name='report_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='reports.reporttype'),
        ),
        migrations.AddField(
            model_name='question',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='reports.reportsection'),
        ),
        migrations.CreateModel(
            name='ConditionalRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('trigger_value', models.CharField(max_length=255)),
                ('action', models.CharField(choices=[('show', 'Show Question'), ('hide', 'Hide Question'), ('require', 'Make Required'), ('unrequire', 'Make Optional')], max_length=20)),
                ('report_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conditional_rules', to='reports.reporttype')),
                ('target_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conditional_targets', to='reports.question')),
                ('trigger_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conditional_triggers', to='reports.question')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('text_answer', models.TextField(blank=True, null=True)),
                ('file_answer', models.FileField(blank=True, null=True, upload_to='report_answers/')),
                ('signature_answer', models.FileField(blank=True, null=True, upload_to='report_signatures/')),
                ('date_answer', models.DateField(blank=True, null=True)),
                ('number_answer', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='reports.question')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='reports.report')),
                ('selected_options', models.ManyToManyField(blank=True, related_name='answers', to='reports.questionoption')),
            ],
            options={
                'unique_together': {('report', 'question')},
            },
        ),
    ]
