# Generated by Django 4.2.7 on 2025-07-20 06:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chemsapp', '0002_post_author'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='conditionalrule',
            options={'ordering': ['order', 'name']},
        ),
        migrations.AddField(
            model_name='conditionalrule',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='conditionalrule',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Order in which rules are applied'),
        ),
        migrations.AddField(
            model_name='conditionalrule',
            name='trigger_operator',
            field=models.CharField(choices=[('equals', 'Equals'), ('not_equals', 'Does Not Equal'), ('contains', 'Contains'), ('not_contains', 'Does Not Contain'), ('greater_than', 'Greater Than'), ('less_than', 'Less Than'), ('is_empty', 'Is Empty'), ('is_not_empty', 'Is Not Empty')], default='equals', max_length=20),
        ),
        migrations.AlterField(
            model_name='conditionalrule',
            name='action',
            field=models.CharField(choices=[('show', 'Show Question'), ('hide', 'Hide Question'), ('require', 'Make Required'), ('unrequire', 'Make Optional'), ('skip_to', 'Skip To Question')], max_length=20),
        ),
        migrations.AlterField(
            model_name='conditionalrule',
            name='trigger_value',
            field=models.CharField(help_text='Value that triggers this rule', max_length=255),
        ),
        migrations.CreateModel(
            name='QuestionTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text="Template name (e.g., 'Standard Temperature Check')", max_length=255)),
                ('category', models.CharField(choices=[('temperature', 'Temperature Monitoring'), ('cleanliness', 'Cleanliness & Sanitation'), ('equipment', 'Equipment Check'), ('safety', 'Safety Compliance'), ('documentation', 'Documentation'), ('general', 'General Inspection'), ('custom', 'Custom')], default='general', max_length=100)),
                ('question_text', models.TextField()),
                ('question_type', models.CharField(choices=[('text', 'Text Input'), ('textarea', 'Long Text'), ('select', 'Select Dropdown'), ('radio', 'Multiple Choice (Radio)'), ('checkbox', 'Multiple Choice (Checkbox)'), ('yesno', 'Yes/No'), ('file', 'File Upload'), ('signature', 'Digital Signature'), ('date', 'Date'), ('number', 'Number'), ('client_select', 'Client Select')], max_length=20)),
                ('help_text', models.TextField(blank=True, null=True)),
                ('is_required_default', models.BooleanField(default=False, help_text='Default required status when using template')),
                ('template_options', models.JSONField(blank=True, default=list, help_text='Default options as JSON array')),
                ('usage_count', models.PositiveIntegerField(default=0)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_templates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ReportTypeCustomer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('assigned_date', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, help_text='Optional notes about this assignment', null=True)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='report_assignments_made', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_type_assignments', to='chemsapp.customer')),
                ('report_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_assignments', to='reports.reporttype')),
            ],
            options={
                'ordering': ['report_type__name', 'customer__businessName'],
                'unique_together': {('report_type', 'customer')},
            },
        ),
    ]
