# Generated by Django 4.2.7 on 2025-08-13 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_alter_conditionalrule_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='show_when_parent_values',
            field=models.JSONField(blank=True, default=list, help_text='Show this question when parent has any of these values'),
        ),
        migrations.AlterField(
            model_name='question',
            name='show_when_parent_value',
            field=models.CharField(blank=True, help_text='DEPRECATED: Use show_when_parent_values instead', max_length=255, null=True),
        ),
    ]
