# Generated by Django 4.2.7 on 2025-08-13 04:55

from django.db import migrations


def migrate_single_to_multiple_values(apps, schema_editor):
    """Convert existing single show_when_parent_value to multiple values format"""
    Question = apps.get_model('reports', 'Question')
    
    questions_to_update = Question.objects.filter(
        show_when_parent_value__isnull=False,
        show_when_parent_values__isnull=True
    ).exclude(show_when_parent_value='')
    
    for question in questions_to_update:
        # Convert single value to list format
        single_value = question.show_when_parent_value
        question.show_when_parent_values = [single_value]
        question.save(update_fields=['show_when_parent_values'])


def reverse_migrate_single_to_multiple_values(apps, schema_editor):
    """Convert multiple values back to single value (for rollback)"""
    Question = apps.get_model('reports', 'Question')
    
    questions_to_update = Question.objects.filter(
        show_when_parent_values__isnull=False
    ).exclude(show_when_parent_values=[])
    
    for question in questions_to_update:
        # Take the first value from the list
        if question.show_when_parent_values:
            question.show_when_parent_value = question.show_when_parent_values[0]
            question.save(update_fields=['show_when_parent_value'])


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_question_show_when_parent_values_and_more'),
    ]

    operations = [
        migrations.RunPython(
            migrate_single_to_multiple_values,
            reverse_migrate_single_to_multiple_values,
        ),
    ]
