# Generated by Django 4.2.7 on 2025-08-31 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_migrate_single_to_multiple_values'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='attachment',
            field=models.FileField(blank=True, help_text='Optional file attachment (photo, document, etc.)', null=True, upload_to='answer_attachments/'),
        ),
        migrations.AddField(
            model_name='answer',
            name='notes',
            field=models.TextField(blank=True, help_text='Additional notes or comments for this answer', null=True),
        ),
    ]
