# Generated by Django 4.2.7 on 2025-09-26 20:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chemsapp', '0002_post_author'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reports', '0005_answer_attachment_answer_notes'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportTypeDistributor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('assigned_date', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, help_text='Optional notes about this assignment', null=True)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='distributor_report_assignments_made', to=settings.AUTH_USER_MODEL)),
                ('distributor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_type_assignments', to='chemsapp.distributor')),
                ('report_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='distributor_assignments', to='reports.reporttype')),
            ],
            options={
                'ordering': ['report_type__name', 'distributor__businessName'],
                'unique_together': {('report_type', 'distributor')},
            },
        ),
    ]
