# Generated by Django 4.2.7 on 2025-09-26 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0006_reporttypedistributor'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='pdf_file',
            field=models.FileField(blank=True, help_text='Generated PDF of the report', null=True, upload_to='report_pdfs/'),
        ),
        migrations.AddField(
            model_name='report',
            name='pdf_generated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='pdf_needs_regeneration',
            field=models.BooleanField(default=True, help_text='True if PDF needs to be regenerated due to changes'),
        ),
    ]
