# Generated by Django 4.2.7 on 2025-09-26 20:44

from django.db import migrations
import logging

logger = logging.getLogger(__name__)


def generate_pdfs_for_existing_reports(apps, schema_editor):
    """Generate PDFs for all existing reports that don't have them"""
    Report = apps.get_model('reports', 'Report')

    reports_without_pdf = Report.objects.filter(pdf_file__isnull=True)
    total_reports = reports_without_pdf.count()

    logger.info(f"Found {total_reports} reports without PDFs. Generating PDFs...")

    generated_count = 0
    error_count = 0

    for report in reports_without_pdf:
        try:
            # Import here to avoid issues with apps registry
            from reports.models import Report as ActualReport

            # Get the actual model instance to call generate_pdf
            actual_report = ActualReport.objects.get(pk=report.pk)

            if actual_report.generate_pdf():
                generated_count += 1
                logger.info(f"Generated PDF for report {actual_report.document_number}")
            else:
                error_count += 1
                logger.warning(f"Failed to generate PDF for report {actual_report.document_number}")

        except Exception as e:
            error_count += 1
            logger.error(f"Error generating PDF for report ID {report.pk}: {str(e)}")

    logger.info(f"PDF generation complete. Generated: {generated_count}, Errors: {error_count}")


def reverse_pdf_generation(apps, schema_editor):
    """Reverse migration - remove generated PDFs"""
    Report = apps.get_model('reports', 'Report')

    # Clear all PDF fields
    Report.objects.update(
        pdf_file=None,
        pdf_generated_at=None,
        pdf_needs_regeneration=True
    )


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0007_report_pdf_file_report_pdf_generated_at_and_more'),
    ]

    operations = [
        migrations.RunPython(
            generate_pdfs_for_existing_reports,
            reverse_pdf_generation,
            hints={'target_db': 'default'}
        ),
    ]
