# Generated by Django 4.2.7 on 2025-11-03 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0008_auto_20250926_2044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('text', 'Text Input'), ('textarea', 'Long Text'), ('select', 'Select Dropdown'), ('radio', 'Multiple Choice (Radio)'), ('checkbox', 'Multiple Choice (Checkbox)'), ('yesno', 'Yes/No'), ('file', 'File Upload'), ('signature', 'Digital Signature'), ('date', 'Date'), ('number', 'Number')], max_length=20),
        ),
        migrations.AlterField(
            model_name='questiontemplate',
            name='question_type',
            field=models.CharField(choices=[('text', 'Text Input'), ('textarea', 'Long Text'), ('select', 'Select Dropdown'), ('radio', 'Multiple Choice (Radio)'), ('checkbox', 'Multiple Choice (Checkbox)'), ('yesno', 'Yes/No'), ('file', 'File Upload'), ('signature', 'Digital Signature'), ('date', 'Date'), ('number', 'Number')], max_length=20),
        ),
    ]
