# Generated by Django 4.2.7 on 2025-11-03 05:46

from django.db import migrations


def delete_client_select_questions(apps, schema_editor):
    """Delete all questions with question_type='client_select'"""
    Question = apps.get_model('reports', 'Question')
    QuestionTemplate = apps.get_model('reports', 'QuestionTemplate')

    # Delete Question instances
    deleted_questions = Question.objects.filter(question_type='client_select').delete()
    print(f"Deleted {deleted_questions[0]} Question(s) with type 'client_select'")

    # Delete QuestionTemplate instances
    deleted_templates = QuestionTemplate.objects.filter(question_type='client_select').delete()
    print(f"Deleted {deleted_templates[0]} QuestionTemplate(s) with type 'client_select'")


def reverse_migration(apps, schema_editor):
    """Cannot reverse deletion of questions"""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0009_alter_question_question_type_and_more'),
    ]

    operations = [
        migrations.RunPython(delete_client_select_questions, reverse_migration),
    ]
