# Generated by Django 4.2.7 on 2025-12-06 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0010_delete_client_select_questions'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionoption',
            name='badge_type',
            field=models.CharField(choices=[('default', 'Default (No Badge)'), ('pass', 'Pass (Green)'), ('fail', 'Fail (Red)'), ('warning', 'Warning (Orange)'), ('info', 'Info (Blue)'), ('data', 'Data (Gray)')], default='default', help_text='Badge color to display in PDF report', max_length=20),
        ),
        migrations.AlterField(
            model_name='questionoption',
            name='is_flag',
            field=models.BooleanField(default=False, help_text='Mark this option as requiring attention (will appear in Flagged Items page)'),
        ),
    ]
