# Generated by Django 4.2.7 on 2025-12-13 00:04

from django.db import migrations


def set_all_reports_to_submitted(apps, schema_editor):
    """Set all existing reports to 'submitted' status"""
    Report = apps.get_model('reports', 'Report')
    # Get the status value from REPORT_STATUS choices
    # REPORT_STATUS = [('draft', 'Draft'), ('submitted', 'Submitted'), ...]
    from reports.models import REPORT_STATUS
    submitted_status = [status[0] for status in REPORT_STATUS if status[1] == 'Submitted'][0]
    # Update all reports to submitted status
    Report.objects.all().update(status=submitted_status)


def reverse_func(apps, schema_editor):
    """Reverse migration - set back to draft"""
    Report = apps.get_model('reports', 'Report')
    from reports.models import REPORT_STATUS
    draft_status = [status[0] for status in REPORT_STATUS if status[1] == 'Draft'][0]
    Report.objects.all().update(status=draft_status)


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0011_questionoption_badge_type_and_more'),
    ]

    operations = [
        migrations.RunPython(set_all_reports_to_submitted, reverse_func),
    ]
