# Generated by Django 4.2.7 on 2025-12-21 04:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chemsapp', '0003_alter_product_description_alter_product_directions'),
        ('reports', '0012_set_all_reports_to_submitted'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComplianceManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='Full name of the compliance manager', max_length=255)),
                ('phone_number', models.CharField(blank=True, help_text='Contact phone number', max_length=50, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compliance_managers', to='chemsapp.customer')),
            ],
            options={
                'verbose_name': 'Compliance Manager',
                'verbose_name_plural': 'Compliance Managers',
                'ordering': ['name'],
            },
        ),
    ]
