# Generated by Django 4.2.7 on 2025-12-21 04:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0013_compliancemanager'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='compliance_manager',
            field=models.ForeignKey(blank=True, help_text="Select a compliance manager from the customer's list", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='reports.compliancemanager'),
        ),
        migrations.AlterField(
            model_name='report',
            name='store_compliance_manager',
            field=models.CharField(blank=True, help_text='Manual entry for compliance manager name (used if no compliance manager is selected)', max_length=255, null=True),
        ),
    ]
