# Generated by Django 4.2.7 on 2026-01-09 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0014_report_compliance_manager_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reporttypedistributor',
            options={'ordering': ['report_type__name', 'distributor__businessname']},
        ),
    ]
