# Generated by Django 4.2.7 on 2026-04-02 20:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0015_alter_reporttypedistributor_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnswerAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(upload_to='answer_attachments/')),
                ('caption', models.CharField(blank=True, default='', max_length=255)),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='reports.answer')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
