# Generated by Django 4.2.7 on 2026-04-02 20:33

from django.db import migrations


def forwards(apps, schema_editor):
    Answer = apps.get_model('reports', 'Answer')
    AnswerAttachment = apps.get_model('reports', 'AnswerAttachment')
    for answer in Answer.objects.exclude(attachment='').exclude(attachment__isnull=True):
        AnswerAttachment.objects.create(answer=answer, file=answer.attachment)


def backwards(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0016_answerattachment'),
    ]

    operations = [
        migrations.RunPython(forwards, backwards),
    ]
