# Generated by Django 4.2.7 on 2026-10-02 22:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reports', '0017_migrate_attachments_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='crm_pushed_at',
            field=models.DateTimeField(blank=True, help_text='When this report was pushed to OnePageCRM as a lead', null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='sales_emailed_at',
            field=models.DateTimeField(blank=True, help_text='When this report was emailed to sales@geller.co.nz', null=True),
        ),
        migrations.AddField(
            model_name='reporttype',
            name='category',
            field=models.CharField(choices=[('standard', 'Standard Report'), ('site_assessment', 'Site Assessment')], default='standard', help_text='Standard reports are filled out for existing customers. Site Assessments are for prospective businesses and are pushed to the CRM/sales on submission.', max_length=20),
        ),
        migrations.CreateModel(
            name='Prospect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business_name', models.CharField(max_length=255)),
                ('address', models.CharField(blank=True, default='', max_length=500)),
                ('phone', models.CharField(blank=True, default='', max_length=100)),
                ('google_place_id', models.CharField(blank=True, default='', help_text='Google Places place_id, if the business was found via search', max_length=255)),
                ('maps_link', models.URLField(blank=True, default='', help_text='Link to view this business on Google Maps', max_length=1000)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prospects_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['business_name'],
            },
        ),
        migrations.AddField(
            model_name='report',
            name='prospect',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='reports.prospect'),
        ),
    ]
