# Generated by Django 4.2.7 on 2026-03-13 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerorder',
            name='submitted',
            field=models.BooleanField(default=False),
        ),
    ]
