# Generated by Django 4.2.7 on 2026-06-20 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_orderlineitem_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderlineitem',
            name='max_stock_level',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='orderlineitem',
            name='soh',
            field=models.IntegerField(default=0),
        ),
    ]
