# Generated by Django 4.2.7 on 2026-08-02 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chemsapp', '0020_applicationtype_dilutionvariant_and_more'),
        ('quotes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quoteline',
            name='dilutions',
            field=models.ManyToManyField(blank=True, related_name='quote_lines', to='chemsapp.dilutionvariant'),
        ),
    ]
