# Generated by Django 4.2.7 on 2026-08-15 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0002_quoteline_dilutions'),
    ]

    operations = [
        migrations.AddField(
            model_name='quoteline',
            name='row_color',
            field=models.CharField(blank=True, default='', max_length=7),
        ),
    ]
